# Find SDL_gles
#
# SDLGLES_INCLUDE_DIR
# SDLGLES_LIBRARY
# SDLGLES_FOUND

FIND_PATH(SDLGLES_INCLUDE_DIR NAMES SDL/SDL_gles.h)

FIND_LIBRARY(SDLGLES_LIBRARY NAMES SDL_gles)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDLGLES DEFAULT_MSG SDLGLES_LIBRARY SDLGLES_INCLUDE_DIR)

MARK_AS_ADVANCED(SDLGLES_INCLUDE_DIR SDLGLES_LIBRARY)
