# Find GLEW
#
# GLEW_INCLUDE_DIR
# GLEW_LIBRARY
# GLEW_FOUND
#

FIND_PATH(GLEW_INCLUDE_DIR NAMES GL/glew.h)

FIND_LIBRARY(GLEW_LIBRARY NAMES GLEW glew glew32 GLEW)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLEW DEFAULT_MSG GLEW_LIBRARY GLEW_INCLUDE_DIR)

MARK_AS_ADVANCED(GLEW_INCLUDE_DIR GLEW_LIBRARY)
