# Find GLES2
#
# GLES2_INCLUDE_DIR
# GLES2_LIBRARY
# GLES2_FOUND

FIND_PATH(GLES2_INCLUDE_DIR NAMES GLES2/gl2.h)

FIND_LIBRARY(GLES2_LIBRARY NAMES GLESv2)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLES2 DEFAULT_MSG GLES2_LIBRARY GLES2_INCLUDE_DIR)

MARK_AS_ADVANCED(GLES2_INCLUDE_DIR GLES2_LIBRARY)
